name: Generate 3D Contribution

on:
  schedule:
    - cron: "0 0 * * *" 
  workflow_dispatch:
  push:
    branches:
      - main
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-github-profile-3d-contrib
    steps:
      - uses: actions/checkout@v3
      
      - name: Generate 3D Contribution Graph
        uses: yoshi3891003/github-profile-3d-contrib@0.7.1
        with:
          github_user_name: ${{ github.repository_owner }}
          # Kita gunakan tema 'dark' agar selaras dengan tema Cyber Anda
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Commit & Push
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add -A .
          git commit -m "Update 3D Contribution Graph" || exit 0
          git push
